### ISSUE TITLE
Extension value

### ISSUE THREAD

**Issue by Galixte** [gothick/phpbb-ext-recaptcha2#26]
Hi @gothick,

since phpBB 3.2.x manages reCaptcha 2 xhat is the advantage to use your extension?

Moreover, what’s the difference betwen master and 3.2.x branches?

However i see in the last release there are a lot of files in ```/vendor/``` folder, is this used?

**Comment by gothick** [comment]
I'm not sure there is any advantage to my extension over the built-in one. I'll update the README to note that the functionality is now in phpBB 3.2—thanks for reminding me!

I only upgraded it to be 3.2.x compatible because it didn't take long and I was doing the others at the weekend :) I'm going to switch my own board to using the built-in one and if it works fine then I'll retire this extension.

Cheers,

Matt

**Comment by Galixte** [comment]
Yeah the only utility from me to use your extension was when i used phpBB 3.1.x, but now, no need. ;)

Regards.

**Comment by Galixte** [comment]
And, please don’t remove your repository, it could be a model for future project, and more important than this, a lot of phpBB boards still use phpBB 3.1.x.

**Comment by gothick** [comment]
Yup, absolutely. I'm going to leave it in place and I've also added to the README a link to the latest release that works with phpBB 3.1.x.

**Comment by Galixte** [comment]
thank you very much. ! ;)
